// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/proto.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account int32

const (
	Account_momo_za_huo_pu Account = 0
)

var Account_name = map[int32]string{
	0: "momo_za_huo_pu",
}

var Account_value = map[string]int32{
	"momo_za_huo_pu": 0,
}

func (x Account) String() string {
	return proto.EnumName(Account_name, int32(x))
}

func (Account) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{0}
}

type R struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *R) Reset()         { *m = R{} }
func (m *R) String() string { return proto.CompactTextString(m) }
func (*R) ProtoMessage()    {}
func (*R) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{0}
}

func (m *R) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R.Unmarshal(m, b)
}
func (m *R) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R.Marshal(b, m, deterministic)
}
func (m *R) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R.Merge(m, src)
}
func (m *R) XXX_Size() int {
	return xxx_messageInfo_R.Size(m)
}
func (m *R) XXX_DiscardUnknown() {
	xxx_messageInfo_R.DiscardUnknown(m)
}

var xxx_messageInfo_R proto.InternalMessageInfo

func (m *R) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *R) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type GetAuthAccessTokenReq struct {
	Account              Account  `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthAccessTokenReq) Reset()         { *m = GetAuthAccessTokenReq{} }
func (m *GetAuthAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAuthAccessTokenReq) ProtoMessage()    {}
func (*GetAuthAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{1}
}

func (m *GetAuthAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAuthAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthAccessTokenReq.Marshal(b, m, deterministic)
}
func (m *GetAuthAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthAccessTokenReq.Merge(m, src)
}
func (m *GetAuthAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAuthAccessTokenReq.Size(m)
}
func (m *GetAuthAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthAccessTokenReq proto.InternalMessageInfo

func (m *GetAuthAccessTokenReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

func (m *GetAuthAccessTokenReq) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type GetAuthAccessTokenRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken         string   `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Openid               string   `protobuf:"bytes,4,opt,name=openid,proto3" json:"openid,omitempty"`
	Scope                string   `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthAccessTokenRes) Reset()         { *m = GetAuthAccessTokenRes{} }
func (m *GetAuthAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAuthAccessTokenRes) ProtoMessage()    {}
func (*GetAuthAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{2}
}

func (m *GetAuthAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAuthAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthAccessTokenRes.Marshal(b, m, deterministic)
}
func (m *GetAuthAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthAccessTokenRes.Merge(m, src)
}
func (m *GetAuthAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAuthAccessTokenRes.Size(m)
}
func (m *GetAuthAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthAccessTokenRes proto.InternalMessageInfo

func (m *GetAuthAccessTokenRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetAuthAccessTokenRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

func (m *GetAuthAccessTokenRes) GetRefreshToken() string {
	if m != nil {
		return m.RefreshToken
	}
	return ""
}

func (m *GetAuthAccessTokenRes) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *GetAuthAccessTokenRes) GetScope() string {
	if m != nil {
		return m.Scope
	}
	return ""
}

type GetUserInfoReq struct {
	AuthAccessToken      string   `protobuf:"bytes,1,opt,name=auth_access_token,json=authAccessToken,proto3" json:"auth_access_token,omitempty"`
	Openid               string   `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoReq) Reset()         { *m = GetUserInfoReq{} }
func (m *GetUserInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoReq) ProtoMessage()    {}
func (*GetUserInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{3}
}

func (m *GetUserInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoReq.Unmarshal(m, b)
}
func (m *GetUserInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoReq.Marshal(b, m, deterministic)
}
func (m *GetUserInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoReq.Merge(m, src)
}
func (m *GetUserInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoReq.Size(m)
}
func (m *GetUserInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoReq proto.InternalMessageInfo

func (m *GetUserInfoReq) GetAuthAccessToken() string {
	if m != nil {
		return m.AuthAccessToken
	}
	return ""
}

func (m *GetUserInfoReq) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

type GetUserInfoRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Openid               string   `protobuf:"bytes,2,opt,name=openid,proto3" json:"openid,omitempty"`
	Nickname             string   `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Headimgurl           string   `protobuf:"bytes,4,opt,name=headimgurl,proto3" json:"headimgurl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserInfoRes) Reset()         { *m = GetUserInfoRes{} }
func (m *GetUserInfoRes) String() string { return proto.CompactTextString(m) }
func (*GetUserInfoRes) ProtoMessage()    {}
func (*GetUserInfoRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{4}
}

func (m *GetUserInfoRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserInfoRes.Unmarshal(m, b)
}
func (m *GetUserInfoRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserInfoRes.Marshal(b, m, deterministic)
}
func (m *GetUserInfoRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserInfoRes.Merge(m, src)
}
func (m *GetUserInfoRes) XXX_Size() int {
	return xxx_messageInfo_GetUserInfoRes.Size(m)
}
func (m *GetUserInfoRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserInfoRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserInfoRes proto.InternalMessageInfo

func (m *GetUserInfoRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetUserInfoRes) GetOpenid() string {
	if m != nil {
		return m.Openid
	}
	return ""
}

func (m *GetUserInfoRes) GetNickname() string {
	if m != nil {
		return m.Nickname
	}
	return ""
}

func (m *GetUserInfoRes) GetHeadimgurl() string {
	if m != nil {
		return m.Headimgurl
	}
	return ""
}

type GetAccessTokenReq struct {
	Account              Account  `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenReq) Reset()         { *m = GetAccessTokenReq{} }
func (m *GetAccessTokenReq) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenReq) ProtoMessage()    {}
func (*GetAccessTokenReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{5}
}

func (m *GetAccessTokenReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenReq.Unmarshal(m, b)
}
func (m *GetAccessTokenReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenReq.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenReq.Merge(m, src)
}
func (m *GetAccessTokenReq) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenReq.Size(m)
}
func (m *GetAccessTokenReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenReq proto.InternalMessageInfo

func (m *GetAccessTokenReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

type GetAccessTokenRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccessTokenRes) Reset()         { *m = GetAccessTokenRes{} }
func (m *GetAccessTokenRes) String() string { return proto.CompactTextString(m) }
func (*GetAccessTokenRes) ProtoMessage()    {}
func (*GetAccessTokenRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{6}
}

func (m *GetAccessTokenRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccessTokenRes.Unmarshal(m, b)
}
func (m *GetAccessTokenRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccessTokenRes.Marshal(b, m, deterministic)
}
func (m *GetAccessTokenRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccessTokenRes.Merge(m, src)
}
func (m *GetAccessTokenRes) XXX_Size() int {
	return xxx_messageInfo_GetAccessTokenRes.Size(m)
}
func (m *GetAccessTokenRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccessTokenRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccessTokenRes proto.InternalMessageInfo

func (m *GetAccessTokenRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetAccessTokenRes) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

type GetTicketReq struct {
	Account              Account  `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketReq) Reset()         { *m = GetTicketReq{} }
func (m *GetTicketReq) String() string { return proto.CompactTextString(m) }
func (*GetTicketReq) ProtoMessage()    {}
func (*GetTicketReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{7}
}

func (m *GetTicketReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketReq.Unmarshal(m, b)
}
func (m *GetTicketReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketReq.Marshal(b, m, deterministic)
}
func (m *GetTicketReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketReq.Merge(m, src)
}
func (m *GetTicketReq) XXX_Size() int {
	return xxx_messageInfo_GetTicketReq.Size(m)
}
func (m *GetTicketReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketReq proto.InternalMessageInfo

func (m *GetTicketReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

type GetTicketRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Ticket               string   `protobuf:"bytes,2,opt,name=ticket,proto3" json:"ticket,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTicketRes) Reset()         { *m = GetTicketRes{} }
func (m *GetTicketRes) String() string { return proto.CompactTextString(m) }
func (*GetTicketRes) ProtoMessage()    {}
func (*GetTicketRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{8}
}

func (m *GetTicketRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTicketRes.Unmarshal(m, b)
}
func (m *GetTicketRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTicketRes.Marshal(b, m, deterministic)
}
func (m *GetTicketRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTicketRes.Merge(m, src)
}
func (m *GetTicketRes) XXX_Size() int {
	return xxx_messageInfo_GetTicketRes.Size(m)
}
func (m *GetTicketRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTicketRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetTicketRes proto.InternalMessageInfo

func (m *GetTicketRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetTicketRes) GetTicket() string {
	if m != nil {
		return m.Ticket
	}
	return ""
}

type GetJssdkReq struct {
	Account              Account  `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJssdkReq) Reset()         { *m = GetJssdkReq{} }
func (m *GetJssdkReq) String() string { return proto.CompactTextString(m) }
func (*GetJssdkReq) ProtoMessage()    {}
func (*GetJssdkReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{9}
}

func (m *GetJssdkReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJssdkReq.Unmarshal(m, b)
}
func (m *GetJssdkReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJssdkReq.Marshal(b, m, deterministic)
}
func (m *GetJssdkReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJssdkReq.Merge(m, src)
}
func (m *GetJssdkReq) XXX_Size() int {
	return xxx_messageInfo_GetJssdkReq.Size(m)
}
func (m *GetJssdkReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJssdkReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetJssdkReq proto.InternalMessageInfo

func (m *GetJssdkReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

func (m *GetJssdkReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type GetJssdkRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Appid                string   `protobuf:"bytes,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Noncestr             string   `protobuf:"bytes,3,opt,name=noncestr,proto3" json:"noncestr,omitempty"`
	Timestamp            string   `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Signature            string   `protobuf:"bytes,5,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetJssdkRes) Reset()         { *m = GetJssdkRes{} }
func (m *GetJssdkRes) String() string { return proto.CompactTextString(m) }
func (*GetJssdkRes) ProtoMessage()    {}
func (*GetJssdkRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{10}
}

func (m *GetJssdkRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetJssdkRes.Unmarshal(m, b)
}
func (m *GetJssdkRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetJssdkRes.Marshal(b, m, deterministic)
}
func (m *GetJssdkRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetJssdkRes.Merge(m, src)
}
func (m *GetJssdkRes) XXX_Size() int {
	return xxx_messageInfo_GetJssdkRes.Size(m)
}
func (m *GetJssdkRes) XXX_DiscardUnknown() {
	xxx_messageInfo_GetJssdkRes.DiscardUnknown(m)
}

var xxx_messageInfo_GetJssdkRes proto.InternalMessageInfo

func (m *GetJssdkRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *GetJssdkRes) GetAppid() string {
	if m != nil {
		return m.Appid
	}
	return ""
}

func (m *GetJssdkRes) GetNoncestr() string {
	if m != nil {
		return m.Noncestr
	}
	return ""
}

func (m *GetJssdkRes) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

func (m *GetJssdkRes) GetSignature() string {
	if m != nil {
		return m.Signature
	}
	return ""
}

type MakeShortUrlReq struct {
	Account              Account  `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeShortUrlReq) Reset()         { *m = MakeShortUrlReq{} }
func (m *MakeShortUrlReq) String() string { return proto.CompactTextString(m) }
func (*MakeShortUrlReq) ProtoMessage()    {}
func (*MakeShortUrlReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{11}
}

func (m *MakeShortUrlReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeShortUrlReq.Unmarshal(m, b)
}
func (m *MakeShortUrlReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeShortUrlReq.Marshal(b, m, deterministic)
}
func (m *MakeShortUrlReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeShortUrlReq.Merge(m, src)
}
func (m *MakeShortUrlReq) XXX_Size() int {
	return xxx_messageInfo_MakeShortUrlReq.Size(m)
}
func (m *MakeShortUrlReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeShortUrlReq.DiscardUnknown(m)
}

var xxx_messageInfo_MakeShortUrlReq proto.InternalMessageInfo

func (m *MakeShortUrlReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

func (m *MakeShortUrlReq) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type MakeShortUrlRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	ShortUrl             string   `protobuf:"bytes,2,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MakeShortUrlRes) Reset()         { *m = MakeShortUrlRes{} }
func (m *MakeShortUrlRes) String() string { return proto.CompactTextString(m) }
func (*MakeShortUrlRes) ProtoMessage()    {}
func (*MakeShortUrlRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{12}
}

func (m *MakeShortUrlRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MakeShortUrlRes.Unmarshal(m, b)
}
func (m *MakeShortUrlRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MakeShortUrlRes.Marshal(b, m, deterministic)
}
func (m *MakeShortUrlRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MakeShortUrlRes.Merge(m, src)
}
func (m *MakeShortUrlRes) XXX_Size() int {
	return xxx_messageInfo_MakeShortUrlRes.Size(m)
}
func (m *MakeShortUrlRes) XXX_DiscardUnknown() {
	xxx_messageInfo_MakeShortUrlRes.DiscardUnknown(m)
}

var xxx_messageInfo_MakeShortUrlRes proto.InternalMessageInfo

func (m *MakeShortUrlRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func (m *MakeShortUrlRes) GetShortUrl() string {
	if m != nil {
		return m.ShortUrl
	}
	return ""
}

type Template struct {
	Touser               string                   `protobuf:"bytes,1,opt,name=touser,proto3" json:"touser,omitempty"`
	TemplateId           string                   `protobuf:"bytes,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Url                  string                   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Data                 map[string]*TemplateItem `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *Template) Reset()         { *m = Template{} }
func (m *Template) String() string { return proto.CompactTextString(m) }
func (*Template) ProtoMessage()    {}
func (*Template) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{13}
}

func (m *Template) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Template.Unmarshal(m, b)
}
func (m *Template) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Template.Marshal(b, m, deterministic)
}
func (m *Template) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Template.Merge(m, src)
}
func (m *Template) XXX_Size() int {
	return xxx_messageInfo_Template.Size(m)
}
func (m *Template) XXX_DiscardUnknown() {
	xxx_messageInfo_Template.DiscardUnknown(m)
}

var xxx_messageInfo_Template proto.InternalMessageInfo

func (m *Template) GetTouser() string {
	if m != nil {
		return m.Touser
	}
	return ""
}

func (m *Template) GetTemplateId() string {
	if m != nil {
		return m.TemplateId
	}
	return ""
}

func (m *Template) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Template) GetData() map[string]*TemplateItem {
	if m != nil {
		return m.Data
	}
	return nil
}

type TemplateItem struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Color                string   `protobuf:"bytes,2,opt,name=color,proto3" json:"color,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TemplateItem) Reset()         { *m = TemplateItem{} }
func (m *TemplateItem) String() string { return proto.CompactTextString(m) }
func (*TemplateItem) ProtoMessage()    {}
func (*TemplateItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{14}
}

func (m *TemplateItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TemplateItem.Unmarshal(m, b)
}
func (m *TemplateItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TemplateItem.Marshal(b, m, deterministic)
}
func (m *TemplateItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TemplateItem.Merge(m, src)
}
func (m *TemplateItem) XXX_Size() int {
	return xxx_messageInfo_TemplateItem.Size(m)
}
func (m *TemplateItem) XXX_DiscardUnknown() {
	xxx_messageInfo_TemplateItem.DiscardUnknown(m)
}

var xxx_messageInfo_TemplateItem proto.InternalMessageInfo

func (m *TemplateItem) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TemplateItem) GetColor() string {
	if m != nil {
		return m.Color
	}
	return ""
}

type SendTemplateReq struct {
	Account              Account   `protobuf:"varint,1,opt,name=account,proto3,enum=Account" json:"account,omitempty"`
	Template             *Template `protobuf:"bytes,2,opt,name=template,proto3" json:"template,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SendTemplateReq) Reset()         { *m = SendTemplateReq{} }
func (m *SendTemplateReq) String() string { return proto.CompactTextString(m) }
func (*SendTemplateReq) ProtoMessage()    {}
func (*SendTemplateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{15}
}

func (m *SendTemplateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTemplateReq.Unmarshal(m, b)
}
func (m *SendTemplateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTemplateReq.Marshal(b, m, deterministic)
}
func (m *SendTemplateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTemplateReq.Merge(m, src)
}
func (m *SendTemplateReq) XXX_Size() int {
	return xxx_messageInfo_SendTemplateReq.Size(m)
}
func (m *SendTemplateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTemplateReq.DiscardUnknown(m)
}

var xxx_messageInfo_SendTemplateReq proto.InternalMessageInfo

func (m *SendTemplateReq) GetAccount() Account {
	if m != nil {
		return m.Account
	}
	return Account_momo_za_huo_pu
}

func (m *SendTemplateReq) GetTemplate() *Template {
	if m != nil {
		return m.Template
	}
	return nil
}

type SendTemplateRes struct {
	Res                  *R       `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendTemplateRes) Reset()         { *m = SendTemplateRes{} }
func (m *SendTemplateRes) String() string { return proto.CompactTextString(m) }
func (*SendTemplateRes) ProtoMessage()    {}
func (*SendTemplateRes) Descriptor() ([]byte, []int) {
	return fileDescriptor_ef32c37ea206d67b, []int{16}
}

func (m *SendTemplateRes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendTemplateRes.Unmarshal(m, b)
}
func (m *SendTemplateRes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendTemplateRes.Marshal(b, m, deterministic)
}
func (m *SendTemplateRes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendTemplateRes.Merge(m, src)
}
func (m *SendTemplateRes) XXX_Size() int {
	return xxx_messageInfo_SendTemplateRes.Size(m)
}
func (m *SendTemplateRes) XXX_DiscardUnknown() {
	xxx_messageInfo_SendTemplateRes.DiscardUnknown(m)
}

var xxx_messageInfo_SendTemplateRes proto.InternalMessageInfo

func (m *SendTemplateRes) GetRes() *R {
	if m != nil {
		return m.Res
	}
	return nil
}

func init() {
	proto.RegisterEnum("Account", Account_name, Account_value)
	proto.RegisterType((*R)(nil), "r")
	proto.RegisterType((*GetAuthAccessTokenReq)(nil), "get_auth_access_token_req")
	proto.RegisterType((*GetAuthAccessTokenRes)(nil), "get_auth_access_token_res")
	proto.RegisterType((*GetUserInfoReq)(nil), "get_user_info_req")
	proto.RegisterType((*GetUserInfoRes)(nil), "get_user_info_res")
	proto.RegisterType((*GetAccessTokenReq)(nil), "get_access_token_req")
	proto.RegisterType((*GetAccessTokenRes)(nil), "get_access_token_res")
	proto.RegisterType((*GetTicketReq)(nil), "get_ticket_req")
	proto.RegisterType((*GetTicketRes)(nil), "get_ticket_res")
	proto.RegisterType((*GetJssdkReq)(nil), "get_jssdk_req")
	proto.RegisterType((*GetJssdkRes)(nil), "get_jssdk_res")
	proto.RegisterType((*MakeShortUrlReq)(nil), "make_short_url_req")
	proto.RegisterType((*MakeShortUrlRes)(nil), "make_short_url_res")
	proto.RegisterType((*Template)(nil), "template")
	proto.RegisterMapType((map[string]*TemplateItem)(nil), "template.DataEntry")
	proto.RegisterType((*TemplateItem)(nil), "template_item")
	proto.RegisterType((*SendTemplateReq)(nil), "send_template_req")
	proto.RegisterType((*SendTemplateRes)(nil), "send_template_res")
}

func init() { proto.RegisterFile("api/proto/proto.proto", fileDescriptor_ef32c37ea206d67b) }

var fileDescriptor_ef32c37ea206d67b = []byte{
	// 740 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdf, 0x6e, 0xd3, 0x3c,
	0x14, 0x5f, 0x9a, 0x76, 0x6b, 0x4f, 0xb7, 0xae, 0xf3, 0xba, 0x4f, 0xfd, 0xf2, 0xfd, 0xdb, 0x67,
	0x40, 0x6c, 0x93, 0x08, 0xa8, 0x70, 0x01, 0x03, 0x21, 0x31, 0x31, 0x4d, 0x70, 0x83, 0x08, 0x20,
	0x24, 0x2e, 0x88, 0x4c, 0xea, 0xb5, 0xa1, 0x4d, 0x1c, 0x6c, 0x07, 0x34, 0x24, 0x9e, 0x82, 0x87,
	0xe0, 0x05, 0x78, 0x07, 0x5e, 0x0b, 0xd9, 0x71, 0xd2, 0x76, 0x69, 0xd0, 0x34, 0x6e, 0x5a, 0x9f,
	0xdf, 0x39, 0xfe, 0xf9, 0xf8, 0xfc, 0x7c, 0x4e, 0x60, 0x87, 0x24, 0xe1, 0xcd, 0x84, 0x33, 0xc9,
	0xb2, 0x5f, 0x57, 0xff, 0xe2, 0x7d, 0xb0, 0x38, 0x42, 0x50, 0x0f, 0xd8, 0x90, 0xf6, 0xad, 0x5d,
	0x6b, 0xcf, 0xf6, 0xf4, 0x1a, 0x75, 0xc1, 0x8e, 0xc4, 0xa8, 0x5f, 0xdb, 0xb5, 0xf6, 0x5a, 0x9e,
	0x5a, 0xe2, 0x17, 0xf0, 0xe7, 0x88, 0x4a, 0x9f, 0xa4, 0x72, 0xec, 0x93, 0x20, 0xa0, 0x42, 0xf8,
	0x92, 0x4d, 0x68, 0xec, 0x73, 0xfa, 0x01, 0x61, 0x58, 0x23, 0x41, 0xc0, 0xd2, 0x58, 0x6a, 0x96,
	0xce, 0xa0, 0xe9, 0x1a, 0xdb, 0xcb, 0x1d, 0xc5, 0x31, 0x19, 0xa7, 0x5e, 0xe3, 0x6f, 0x56, 0x35,
	0xab, 0x40, 0x3d, 0xb0, 0x39, 0x15, 0x9a, 0xb1, 0x3d, 0xa8, 0xb9, 0xdc, 0x53, 0x26, 0xfa, 0x1f,
	0xd6, 0xe7, 0x23, 0x0d, 0x5f, 0x3b, 0xc3, 0x5e, 0x2a, 0x08, 0x5d, 0x81, 0x0d, 0x4e, 0x4f, 0x39,
	0x15, 0x63, 0x13, 0x63, 0xeb, 0x98, 0x75, 0x03, 0x66, 0x41, 0x7f, 0xc0, 0x2a, 0x4b, 0x68, 0x1c,
	0x0e, 0xfb, 0x75, 0xed, 0x35, 0x16, 0xea, 0x41, 0x43, 0x04, 0x2c, 0xa1, 0xfd, 0x86, 0x86, 0x33,
	0x03, 0xbf, 0x86, 0x2d, 0x95, 0x68, 0x2a, 0x28, 0xf7, 0xc3, 0xf8, 0x94, 0xe9, 0x6b, 0x1f, 0xc0,
	0x56, 0x29, 0x73, 0x9d, 0x6e, 0xcb, 0xdb, 0x54, 0x8e, 0x47, 0x73, 0x39, 0xcd, 0x8e, 0xab, 0xcd,
	0x1f, 0x87, 0xbf, 0x94, 0x89, 0xab, 0x6e, 0x5e, 0x41, 0x81, 0x1c, 0x68, 0xc6, 0x61, 0x30, 0x89,
	0x49, 0x44, 0xcd, 0x4d, 0x0b, 0x1b, 0xfd, 0x0b, 0x30, 0xa6, 0x64, 0x18, 0x46, 0xa3, 0x94, 0x4f,
	0xcd, 0x4d, 0xe7, 0x10, 0x7c, 0x08, 0x3d, 0x2d, 0xc0, 0x25, 0x14, 0xc5, 0xcf, 0x96, 0xee, 0xbd,
	0xbc, 0x6e, 0xf8, 0x0e, 0x74, 0x14, 0xa1, 0x0c, 0x83, 0x09, 0x95, 0x17, 0x4e, 0xe3, 0xe1, 0xb9,
	0x5d, 0xbf, 0x28, 0x5f, 0x16, 0x93, 0x97, 0x2f, 0xb3, 0xf0, 0x31, 0x6c, 0xa8, 0xfd, 0xef, 0x85,
	0x18, 0x4e, 0x2e, 0xfc, 0x9a, 0xbb, 0x60, 0xab, 0x82, 0x9a, 0x06, 0x51, 0x95, 0xfc, 0x6a, 0x2d,
	0xf2, 0x54, 0xa5, 0xd1, 0x83, 0x06, 0x49, 0x92, 0x42, 0xc4, 0xcc, 0xd0, 0x1a, 0xb2, 0x38, 0xa0,
	0x42, 0xf2, 0x42, 0x43, 0x63, 0xa3, 0xbf, 0xa1, 0x25, 0xc3, 0x88, 0x0a, 0x49, 0xa2, 0xc4, 0x48,
	0x38, 0x03, 0x94, 0x57, 0x84, 0xa3, 0x98, 0xc8, 0x94, 0xe7, 0x6f, 0x76, 0x06, 0xe0, 0xa7, 0x80,
	0x22, 0x32, 0xa1, 0xbe, 0x18, 0x33, 0x2e, 0xfd, 0x94, 0x4f, 0x7f, 0xe3, 0x86, 0x27, 0x4b, 0xb8,
	0xaa, 0x6e, 0xf9, 0x17, 0xb4, 0x8a, 0x30, 0xc3, 0xd1, 0xd4, 0xc0, 0x2b, 0x3e, 0xc5, 0x3f, 0x2c,
	0x68, 0x4a, 0x1a, 0x25, 0x53, 0x22, 0xa9, 0x96, 0x85, 0xa9, 0xe7, 0x6f, 0x3a, 0xc7, 0x58, 0xe8,
	0x3f, 0x68, 0xe7, 0x31, 0x7e, 0x51, 0x2d, 0xc8, 0xa1, 0x27, 0xc3, 0x3c, 0x41, 0xbb, 0x48, 0x10,
	0x5d, 0x87, 0xfa, 0x90, 0x48, 0xd2, 0xaf, 0xef, 0xda, 0x7b, 0xed, 0xc1, 0xb6, 0x9b, 0x07, 0xbb,
	0x8f, 0x89, 0x24, 0xc7, 0xb1, 0xe4, 0x67, 0x9e, 0x0e, 0x70, 0x4e, 0xa0, 0x55, 0x40, 0x8a, 0x67,
	0x42, 0xcf, 0xcc, 0xe9, 0x6a, 0x89, 0xae, 0x42, 0xe3, 0x23, 0x99, 0xa6, 0xd9, 0xac, 0x6a, 0x0f,
	0x3a, 0xee, 0x2c, 0x11, 0x49, 0x23, 0x2f, 0x73, 0x1e, 0xd6, 0xee, 0x5a, 0xf8, 0x3e, 0x6c, 0x2c,
	0xf8, 0x94, 0xba, 0xd9, 0xd6, 0x8c, 0x2e, 0x33, 0x14, 0x1a, 0xb0, 0x29, 0xe3, 0xb9, 0xe6, 0xda,
	0xc0, 0x6f, 0x61, 0x4b, 0xd0, 0x78, 0xe8, 0x17, 0x0c, 0x17, 0x95, 0xe6, 0xda, 0xac, 0x7c, 0x26,
	0xc5, 0x56, 0x91, 0xa2, 0x57, 0xb8, 0xf0, 0x7e, 0x99, 0xbf, 0x42, 0xae, 0x83, 0x7f, 0x60, 0x6e,
	0x4e, 0x77, 0x22, 0x16, 0x31, 0xff, 0x33, 0xf1, 0xc7, 0x29, 0xf3, 0x93, 0xb4, 0xbb, 0x32, 0xf8,
	0x6e, 0xc3, 0xea, 0x27, 0x1a, 0x8c, 0x89, 0x44, 0xcf, 0x61, 0x67, 0xe9, 0xc4, 0x46, 0x8e, 0x5b,
	0xf9, 0x7d, 0x70, 0xaa, 0x7d, 0x02, 0xaf, 0xa0, 0x7b, 0x59, 0xe3, 0x14, 0x23, 0x10, 0x21, 0xb7,
	0x34, 0x6b, 0x9d, 0x32, 0xa6, 0xb6, 0x1e, 0x41, 0xf7, 0xfc, 0x08, 0x42, 0x3b, 0xee, 0xb2, 0x89,
	0xe6, 0x2c, 0x85, 0x15, 0xc7, 0x2d, 0x80, 0xd9, 0xfc, 0x40, 0x9b, 0xee, 0xe2, 0x08, 0x72, 0xce,
	0x01, 0x6a, 0xc7, 0x0d, 0x68, 0x15, 0x9d, 0x8e, 0x3a, 0xee, 0xc2, 0xf4, 0x70, 0x16, 0x6d, 0x15,
	0xfe, 0x00, 0x3a, 0x8b, 0x7d, 0x83, 0xb6, 0xdd, 0x72, 0x53, 0x3a, 0x4b, 0x40, 0x53, 0x9d, 0x05,
	0x15, 0x11, 0x72, 0x4b, 0xaf, 0xc6, 0x29, 0x63, 0x02, 0xaf, 0x1c, 0xad, 0xbd, 0x69, 0xe8, 0xef,
	0xfc, 0xbb, 0x55, 0xfd, 0x77, 0xfb, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c, 0xa3, 0xeb, 0xab,
	0x07, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WechatClient is the client API for Wechat service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WechatClient interface {
	GetAuthAccessToken(ctx context.Context, in *GetAuthAccessTokenReq, opts ...grpc.CallOption) (*GetAuthAccessTokenRes, error)
	GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error)
	GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenRes, error)
	GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*GetTicketRes, error)
	GetJssdk(ctx context.Context, in *GetJssdkReq, opts ...grpc.CallOption) (*GetJssdkRes, error)
	MakeShortUrl(ctx context.Context, in *MakeShortUrlReq, opts ...grpc.CallOption) (*MakeShortUrlRes, error)
	SendTemplate(ctx context.Context, in *SendTemplateReq, opts ...grpc.CallOption) (*SendTemplateRes, error)
}

type wechatClient struct {
	cc *grpc.ClientConn
}

func NewWechatClient(cc *grpc.ClientConn) WechatClient {
	return &wechatClient{cc}
}

func (c *wechatClient) GetAuthAccessToken(ctx context.Context, in *GetAuthAccessTokenReq, opts ...grpc.CallOption) (*GetAuthAccessTokenRes, error) {
	out := new(GetAuthAccessTokenRes)
	err := c.cc.Invoke(ctx, "/wechat/get_auth_access_token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) GetUserInfo(ctx context.Context, in *GetUserInfoReq, opts ...grpc.CallOption) (*GetUserInfoRes, error) {
	out := new(GetUserInfoRes)
	err := c.cc.Invoke(ctx, "/wechat/get_user_info", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) GetAccessToken(ctx context.Context, in *GetAccessTokenReq, opts ...grpc.CallOption) (*GetAccessTokenRes, error) {
	out := new(GetAccessTokenRes)
	err := c.cc.Invoke(ctx, "/wechat/get_access_token", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) GetTicket(ctx context.Context, in *GetTicketReq, opts ...grpc.CallOption) (*GetTicketRes, error) {
	out := new(GetTicketRes)
	err := c.cc.Invoke(ctx, "/wechat/get_ticket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) GetJssdk(ctx context.Context, in *GetJssdkReq, opts ...grpc.CallOption) (*GetJssdkRes, error) {
	out := new(GetJssdkRes)
	err := c.cc.Invoke(ctx, "/wechat/get_jssdk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) MakeShortUrl(ctx context.Context, in *MakeShortUrlReq, opts ...grpc.CallOption) (*MakeShortUrlRes, error) {
	out := new(MakeShortUrlRes)
	err := c.cc.Invoke(ctx, "/wechat/make_short_url", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *wechatClient) SendTemplate(ctx context.Context, in *SendTemplateReq, opts ...grpc.CallOption) (*SendTemplateRes, error) {
	out := new(SendTemplateRes)
	err := c.cc.Invoke(ctx, "/wechat/send_template", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WechatServer is the server API for Wechat service.
type WechatServer interface {
	GetAuthAccessToken(context.Context, *GetAuthAccessTokenReq) (*GetAuthAccessTokenRes, error)
	GetUserInfo(context.Context, *GetUserInfoReq) (*GetUserInfoRes, error)
	GetAccessToken(context.Context, *GetAccessTokenReq) (*GetAccessTokenRes, error)
	GetTicket(context.Context, *GetTicketReq) (*GetTicketRes, error)
	GetJssdk(context.Context, *GetJssdkReq) (*GetJssdkRes, error)
	MakeShortUrl(context.Context, *MakeShortUrlReq) (*MakeShortUrlRes, error)
	SendTemplate(context.Context, *SendTemplateReq) (*SendTemplateRes, error)
}

// UnimplementedWechatServer can be embedded to have forward compatible implementations.
type UnimplementedWechatServer struct {
}

func (*UnimplementedWechatServer) GetAuthAccessToken(ctx context.Context, req *GetAuthAccessTokenReq) (*GetAuthAccessTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthAccessToken not implemented")
}
func (*UnimplementedWechatServer) GetUserInfo(ctx context.Context, req *GetUserInfoReq) (*GetUserInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInfo not implemented")
}
func (*UnimplementedWechatServer) GetAccessToken(ctx context.Context, req *GetAccessTokenReq) (*GetAccessTokenRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccessToken not implemented")
}
func (*UnimplementedWechatServer) GetTicket(ctx context.Context, req *GetTicketReq) (*GetTicketRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTicket not implemented")
}
func (*UnimplementedWechatServer) GetJssdk(ctx context.Context, req *GetJssdkReq) (*GetJssdkRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJssdk not implemented")
}
func (*UnimplementedWechatServer) MakeShortUrl(ctx context.Context, req *MakeShortUrlReq) (*MakeShortUrlRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeShortUrl not implemented")
}
func (*UnimplementedWechatServer) SendTemplate(ctx context.Context, req *SendTemplateReq) (*SendTemplateRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendTemplate not implemented")
}

func RegisterWechatServer(s *grpc.Server, srv WechatServer) {
	s.RegisterService(&_Wechat_serviceDesc, srv)
}

func _Wechat_GetAuthAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).GetAuthAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/GetAuthAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).GetAuthAccessToken(ctx, req.(*GetAuthAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_GetUserInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).GetUserInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/GetUserInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).GetUserInfo(ctx, req.(*GetUserInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_GetAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccessTokenReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).GetAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/GetAccessToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).GetAccessToken(ctx, req.(*GetAccessTokenReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_GetTicket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTicketReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).GetTicket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/GetTicket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).GetTicket(ctx, req.(*GetTicketReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_GetJssdk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJssdkReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).GetJssdk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/GetJssdk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).GetJssdk(ctx, req.(*GetJssdkReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_MakeShortUrl_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MakeShortUrlReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).MakeShortUrl(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/MakeShortUrl",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).MakeShortUrl(ctx, req.(*MakeShortUrlReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Wechat_SendTemplate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendTemplateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WechatServer).SendTemplate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/wechat/SendTemplate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WechatServer).SendTemplate(ctx, req.(*SendTemplateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Wechat_serviceDesc = grpc.ServiceDesc{
	ServiceName: "wechat",
	HandlerType: (*WechatServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "get_auth_access_token",
			Handler:    _Wechat_GetAuthAccessToken_Handler,
		},
		{
			MethodName: "get_user_info",
			Handler:    _Wechat_GetUserInfo_Handler,
		},
		{
			MethodName: "get_access_token",
			Handler:    _Wechat_GetAccessToken_Handler,
		},
		{
			MethodName: "get_ticket",
			Handler:    _Wechat_GetTicket_Handler,
		},
		{
			MethodName: "get_jssdk",
			Handler:    _Wechat_GetJssdk_Handler,
		},
		{
			MethodName: "make_short_url",
			Handler:    _Wechat_MakeShortUrl_Handler,
		},
		{
			MethodName: "send_template",
			Handler:    _Wechat_SendTemplate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/proto.proto",
}
